config/routes.rb
require 'api_constraints'

MultinivelApi::Application.routes.draw do
  devise_for :users
  mount SabisuRails::Engine => "/sabisu_rails"
# Api definition
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
      resources :banks

      resources :users, :only => [:show, :create, :update, :destroy]
      resources :sessions, :only => [:create, :destroy]

      get '/auth/:provider/callback', to: 'sessions#create'
    end
  end
end

app/models/bank.rb
class Bank < ActiveRecord::Base
	validates :name, :presence=>true
	resourcify
end

app/controllers/api/v1/banks_controller.rb
class Api::V1::BanksController < ApplicationController
    after_action :verify_authorized, except: [:index, :show]	
    before_action :authenticate_with_token!

	def index
		@banks = Bank.all
        respond_to do |f|
          f.html {}
          f.json { render json: @banks }
       end        
	end

    def new
    	@bank = Bank.new
    end

	def edit
	end


    def show
		@banks = Bank.find(params[:id])

       respond_to do |f|
          f.html {}
          f.json { render json: @banks }
       end        

    end
 
    def create
	    @bank = Bank.new(bank_params)

	    respond_to do |format|
	      if @bank.save
  	         format.html {}	            
             format.json { render json: @bank }
	      else
	        format.html {}
	        format.json { render json: @bank.errors, status: :unprocessable_entity }
	      end
	    end
    end

    def update 
      @bank = Bank.find(params[:id])
      authorize @bank
      respond_to do |format|
      
	      if @bank.update(bank_params)
  	         format.html {}	            
             format.json { render json: @bank }

	      else
	        format.html {}
	        format.json { render json: @bank.errors, status: :unprocessable_entity }
	      end
	  end    

    end


	def destroy
	   @bank = Bank.find(params[:id])
	   @bank.destroy
	   respond_to do |format|
	      format.html { redirect_to banks_path, notice: 'El banco fue eliminado correctamente.' }
	      format.json { head :no_content }
	   end
	end


	private
    def bank_params
      params.require(:bank).permit(:name, :state_id)
    end

    def set_bank 
		@bank = Bank.find(params[:id])
 
    rescue ActiveRecord::RecordNotFound
		flash[:error] = "El banco no existe"
		redirect_to banks_path		    	
    end

end

app/controllers/bank_controller.rb
class BankController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
	before_action :set_bank, only: [:edit, :update, :destroy]
	#before_action :authenticate_user!

    respond_to :html, :json
	def index
		@banks = Bank.all
        respond_with(@banks)
	end

    def new
    	@bank = Bank.new
    end

	def edit
	end


    def show
    end
 
    def create
	    @bank = Bank.new(bank_params)

	    respond_to do |format|
	      if @bank.save
	        format.html { redirect_to banks_path, notice: 'Registro Guardado Satisfactoriamente' }
	        format.json { render :index, status: :created, location: @bank }
	      else
	        format.html { render :new }
	        format.json { render json: @bank.errors, status: :unprocessable_entity }
	      end
	    end
    end

    def update 
      @bank = Bank.find(params[:id])

      respond_to do |format|
      
	      if @bank.update(bank_params)
	        format.html { redirect_to banks_path, notice: 'Registro Guardado Satisfactoriamente' }
	        format.json { render :index, status: :ok, location: @bank }
	      else
	        format.html { render :edit}
	        format.json { render json: @bank.errors, status: :unprocessable_entity }
	      end
	  end    

    end


	def destroy
	   @bank = Bank.find(params[:id])
	   @bank.destroy
	   respond_to do |format|
	      format.html { redirect_to banks_path, notice: 'El banco fue eliminado correctamente.' }
	      format.json { head :no_content }
	   end
	end


	private
    def bank_params
      params.require(:bank).permit(:name, :state_id)
    end

    def set_bank 
		@bank = Bank.find(params[:id])
 
    rescue ActiveRecord::RecordNotFound
		flash[:error] = "El banco no existe"
		redirect_to banks_path		    	
    end

end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<%= form_for @bank do |f| %>
<%= render 'shared/error_messages', object: @bank %>
  <div class="form-group">
    <%= f.label :name, 'Nombre:' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= @bank.name %></h1>
  </div>

  <%= render 'shared/flash_messages'%>
  
  <div class="panel-body">
    <p>
      <%= link_to "Regresar al listado", :action => "index" %>
    </p>
  </div>

  <%= render 'form' %>
</div>

app/views/banks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Listado de Bancos</h1>
  </div>

    <%= render 'shared/flash_messages'%>
    <p>
      <%= link_to 'Agregar banco', new_bank_path %>
    </p>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
      <% @banks.each do |bank| %>
        <tr>
          <td>
            <%= link_to bank.name, {:action=>"edit", :controller=>"banks", :id=>bank.id} %>
          </td>
          <td class="item">
            <%= link_to 'Editar', {:action=>"edit", :controller=>"banks", :id=>bank.id} %>
            <%= link_to 'Eliminar', bank, method: :delete, :id => "del" + bank.id.to_s %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/banks/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Agregar un banco</h1>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to "Regresar al listado", :action => "index" %>
    </p>
  </div>

  <%= render 'form' %>
</div>