config/routes.rb
require 'api_constraints'

MultinivelApi::Application.routes.draw do
  devise_for :users
  mount SabisuRails::Engine => "/sabisu_rails"
# Api definition
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
      resources :banks

      resources :users, :only => [:show, :create, :update, :destroy]
      resources :sessions, :only => [:create, :destroy]

      get '/auth/:provider/callback', to: 'sessions#create'
    end
  end
end

app/models/associate.rb
# == Schema Information
#
# Table name: associates
#
#  id             :integer          not null, primary key
#  name           :string
#  admission_date :date
#  phone          :string
#  address        :string
#  zip_code       :string
#  email          :string
#  account_number :string
#  clabe          :string
#  is_supervisor  :boolean
#  supervisor_id  :integer
#  city_id        :integer
#  bank_id        :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class Associate < ActiveRecord::Base
  attr_accessor :username
  attr_accessor :password

  has_many :associates, class_name: 'Associate', foreign_key: 'supervisor_id'
  belongs_to :supervisor, class_name: 'Associate'
  belongs_to :city

  has_one    :user
  accepts_nested_attributes_for :user

  before_save { self.email = email.downcase }
  

  validates :name, presence:  true, length: { maximum: 100 }
  validates :phone, presence: true
  validates :email, presence: true

  validates :supervisor_id, numericality: { only_integer: true }
  validates :supervisor_id, presence: true

  validates :city_id, numericality: {only_integer: true}
  validates :city_id, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } 


end

app/models/bank.rb
class Bank < ActiveRecord::Base
	validates :name, :presence=>true
	resourcify
end

app/models/city.rb
class City < ActiveRecord::Base
	validates :name, :presence=>true
	belongs_to :state
end

app/models/commission.rb
# == Schema Information
#
# Table name: commissions
#
#  id                     :integer          not null, primary key
#  purchase_amount        :decimal(, )
#  calculation_start_date :date
#  calculation_end_date   :date
#  amount                 :decimal(, )
#  type_id                :integer
#  payed                  :boolean
#  created_at             :datetime
#  updated_at             :datetime
#

class Commission < ActiveRecord::Base
  belongs_to :type
end

app/models/commission_type.rb
# == Schema Information
#
# Table name: commission_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class CommissionType < ActiveRecord::Base
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  name       :string
#  rfc        :string
#  address    :string
#  telephone  :string
#  email      :string
#  created_at :datetime
#  updated_at :datetime
#

class Company < ActiveRecord::Base
end

app/models/payment_type.rb
# == Schema Information
#
# Table name: payment_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class PaymentType < ActiveRecord::Base
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                    :integer          not null, primary key
#  name                  :string
#  price                 :float
#  description           :text
#  purchase_min_quantity :integer
#  created_at            :datetime
#  updated_at            :datetime
#

class Product < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/state.rb
# == Schema Information
#
# Table name: states
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class State < ActiveRecord::Base
   has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :auth_token, uniqueness: true          

  before_create :generate_authentication_token!
  enum role: [:admin, :client, :supervisor]
  rolify :before_add => :set_default_role

  def generate_authentication_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end

  def set_default_role(role)
      #self.role ||= :client
  end

  def getRolesByUser()
    roles_names = ''
    self.roles.each do |role|
      roles_names += "#{role.name} "
    end
    roles_names.strip()
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

	def bootstrap_version

		"3.2.0"

	end

end

app/helpers/principals_helper.rb
module PrincipalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>Multinivel</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1" />

  <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta description="Sistema de Multinivel. Grupo Sanne" />

</head>

<style>
    .navbar-default {
        background-color: /*#9b2dc7*/ #48176D;
        border-color: #8e44ad;
    }
    .navbar-default .navbar-brand {
        color: #ecf0f1;
    }
    .navbar-default .navbar-brand:hover, .navbar-default .navbar-brand:focus {
        color: #ecdbff;
    }
    .navbar-default .navbar-text {
        color: #ecf0f1;
    }
    .navbar-default .navbar-nav > li > a {
        color: #ecf0f1;
    }
    .navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus {
        color: #ecdbff;
    }
    .navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:hover, .navbar-default .navbar-nav > .active > a:focus {
        color: #ecdbff;
        background-color: #8e44ad;
    }
    .navbar-default .navbar-nav > .open > a, .navbar-default .navbar-nav > .open > a:hover, .navbar-default .navbar-nav > .open > a:focus {
        color: #ecdbff;
        background-color: #8e44ad;
    }
    .navbar-default .navbar-toggle {
        border-color: #8e44ad;
    }
    .navbar-default .navbar-toggle:hover, .navbar-default .navbar-toggle:focus {
        background-color: #8e44ad;
    }
    .navbar-default .navbar-toggle .icon-bar {
        background-color: #ecf0f1;
    }
    .navbar-default .navbar-collapse,
    .navbar-default .navbar-form {
        border-color: #ecf0f1;
    }
    .navbar-default .navbar-link {
        color: #ecf0f1;
    }
    .navbar-default .navbar-link:hover {
        color: #ecdbff;
    }

    @media (max-width: 767px) {
        .navbar-default .navbar-nav .open .dropdown-menu > li > a {
            color: #ecf0f1;
        }
        .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover, .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
            color: #ecdbff;
        }
        .navbar-default .navbar-nav .open .dropdown-menu > .active > a, .navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover, .navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
            color: #ecdbff;
            background-color: #8e44ad;
        }
    }
</style>

<body>

<header>
    <div id="linea_superior_naranja">
    </div>
    <div id="linea_superior_morada">
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Aqui va la imagen en pequeño</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Empresa <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                </ul>
              </li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Catálogos <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Bancos", banks_path, method: 'get' %></li>
                  <li><%= link_to "Ciudades", cities_path, method: 'get' %></li>
                  <li><%= link_to "Empresas", companies_path, method: 'get' %></li>
                  <li><%= link_to "Tipos de Pagos", payment_types_path, method: 'get' %></li>
                  <li><%= link_to "Estados", states_path, method: 'get' %></li>
                </ul>
              </li>
              <li><%= link_to "Logout", destroy_user_session_path, method: 'delete' %></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

    </div>

</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<section id="seccionContenido" class="container">
   <div id="contenido">
     <%= yield %>
   </div>
</section>



<!-- FOOTER-->
<footer id="footer">
<div class="container">
  <div class="row">    
    <div class="col-xs-6 col-md-4 column">          
        <h4>Servicio al cliente</h4>
        <ul class="nav">
          <li><a href="#">Información de envío</a></li>
          <li><a href="#">Política de privacidad</a></li>
          <li><a href="#">Términos y condiciones</a></li>
        </ul> 
      </div>
    <div class="col-xs-6 col-sm-6 col-md-4 column">          
        <h4>Datos de la empresa</h4>
        <ul class="nav">
          <li><a href="about-us.html">Acerca de la empresa</a></li>
          <li><a href="about-us.html">Historia</a></li>
          <li><a href="about-us.html">Clientes</a></li>
        </ul> 
      </div>
    <div class="col-xs-6 col-md-4 column">          
        <h4>Redes sociales</h4>
        <ul class="nav">
           <li><a href="#">Twitter</a></li>
           <li><a href="#">Facebook</a></li>
           <li><a href="#">Google+</a></li>
        </ul> 
      </div>
  </div>
</div>
<div id = "pie">
Grupo SANNE. Todos los derechos reservados
</div>
</footer><!-- /Footer-->

<script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>


<script language="JavaScript" type="text/javascript">



</script>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>Multinivel PARTE PÚBLICA</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1" />

  <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta description="Sistema de Multinivel. Grupo Sanne" />

</head>
<body>

<header>
  <div id="linea_superior_naranja">
  </div>
  <div id="linea_superior_morada">
  </div>
  <div id="contenido">
    <figure id="logo">
      <%= image_tag("logo_sanne_movil.png") %>
    </figure>

    <div id="menu">
      <nav>
        <ul>
          <li><a id="linkZonaEmpresarios" href="#">Zona de Empresarios</a></li>
          <li><a id="menuLogin" href="#">Beneficios</a></li>
          <li><a href="#">Preguntas Frecuentes</a></li>
          <li><a href="#">Plan de trabajo</a></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: 'delete' %></li>
        </ul>
      </nav>
    </div>

  </div>

  <div id="loggeo">
  </div>
</header>

<section id="seccionPrincipal">
  <section id="contenido">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </section>
</section>



<!-- FOOTER-->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-md-4 column">
        <h4>Servicio al cliente</h4>
        <ul class="nav">
          <li><a href="#">Información de envío</a></li>
          <li><a href="#">Política de privacidad</a></li>
          <li><a href="#">Términos y condiciones</a></li>
        </ul>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-4 column">
        <h4>Datos de la empresa</h4>
        <ul class="nav">
          <li><a href="about-us.html">Acerca de la empresa</a></li>
          <li><a href="about-us.html">Historia</a></li>
          <li><a href="about-us.html">Clientes</a></li>
        </ul>
      </div>
      <div class="col-xs-6 col-md-4 column">
        <h4>Redes sociales</h4>
        <ul class="nav">
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
          <li><a href="#">Google+</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div id = "pie">
    Grupo SANNE. Todos los derechos reservados
  </div>
</footer><!-- /Footer-->

<script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>


<script language="JavaScript" type="text/javascript">



</script>

</body>
</html>